GhamdanAlYamaniProject/Controllers/AdminController.cs
using GhamdanAlYamaniProject.Models;
using GhamdanAlYamaniProject.Models.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GhamdanAlYamaniProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly IBaseRepository<Admin> _repo;
        public AdminController(IBaseRepository<Admin> repository)
        {
            _repo = repository;
        }
        public IActionResult Index()
        {
            var admin = _repo.GetAll();
            return View(admin);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(Admin admin)
        {
            if (ModelState.IsValid)
            {
                _repo.Add(admin);
                return RedirectToAction("Index");
            }

            return View(admin);
        }
        public IActionResult Edit(int Id)
        {
            var admin = _repo.Find(Id);
            return View(admin);
        }
        [HttpPost]
        public IActionResult Edit(Admin admin)
        {
            if (ModelState.IsValid)
            {
                _repo.Update(admin);
                return RedirectToAction("Index");
            }

            return View(admin);
        }
        public IActionResult Delete(int Id)
        {
            var admin = _repo.Find(Id);
            return View(admin);
        }
        [HttpPost]
        public IActionResult Delete(Admin admin)
        {
            _repo.Delete(admin);
            return RedirectToAction("index");
        }
    }
}

GhamdanAlYamaniProject/Controllers/BookStorController.cs
using GhamdanAlYamaniProject.Data;
using GhamdanAlYamaniProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GhamdanAlYamaniProject.Controllers
{
    public class BookStorController : Controller
    {
        private readonly ProjectDbContext _context;
        public BookStorController(ProjectDbContext ctx)
        {
            _context = ctx;
        }
        public IActionResult Index()
        {
            ViewBag.catagory = _context.Catagorys;
            return View();
        }
        public IActionResult Create()
        {
            ViewBag.catagory = _context.Catagorys;
            return View();
        }
        [HttpPost]
        public IActionResult Create(BookStor bookstor)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.catagory = _context.Catagorys;
                return View(bookstor);
            }
            if (bookstor.BS_Type == 1)
            {
                bookstor.BS_Num *= -1;
            }
            _context.BookStors.Add(bookstor);
            _context.SaveChanges();
             
            return RedirectToAction("Index","Books");
        }

        public JsonResult LoadBookByCat(int Id)
        {
            var book = _context.Book.Where(p => p.Cat_Id == Id);
            return Json(new SelectList(book, "B_Id", "B_Name"));
        }
    }
}

GhamdanAlYamaniProject/Controllers/BooksController.cs
using GhamdanAlYamaniProject.Models;
using GhamdanAlYamaniProject.Models.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GhamdanAlYamaniProject.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBaseRepository<Books> _repo;
        private readonly IBaseRepository<Catagory> _catRepo;
        private readonly IBaseRepository<Admin> _adminRepo;
        
        public BooksController(IBaseRepository<Books> repository,
            IBaseRepository<Catagory> catRepo,
            IBaseRepository<Admin> adminRepo)
        {
            _repo = repository;
            _catRepo = catRepo;
            _adminRepo = adminRepo;
        }
        public IActionResult Index()
        {
            var books = _repo.GetAll();
            return View(books);
        }

        public IActionResult Details(int Id)
        {
            var book = _repo.Find(Id);
            return View(book);
        }

        public IActionResult Create()
        {
            ViewBag.catagory = _catRepo.GetAll();
            ViewBag.admin = _adminRepo.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Books books)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.catagory = _catRepo.GetAll();
                ViewBag.admin = _adminRepo.GetAll();
                return View(books);
            }
            _repo.Add(books);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int Id)
        {
            ViewBag.catagory = _catRepo.GetAll();
            ViewBag.admin = _adminRepo.GetAll();
            var books = _repo.Find(Id);
            return View(books);
        }
        [HttpPost]
        public IActionResult Edit(Books books)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.catagory = _catRepo.GetAll();
                ViewBag.admin = _adminRepo.GetAll();
                return View(books);
            }
            _repo.Update(books);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int Id)
        {
            ViewBag.catagory = _catRepo.GetAll();
            ViewBag.admin = _adminRepo.GetAll();
            var books = _repo.Find(Id);
            return View(books);
        }

        [HttpPost]
        public IActionResult Delete(Books books)
        {
            _repo.Delete(books);
            return RedirectToAction(nameof(Index));
        }
    }
}

GhamdanAlYamaniProject/Controllers/OrdersController.cs
using GhamdanAlYamaniProject.Models;
using GhamdanAlYamaniProject.Models.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GhamdanAlYamaniProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IBaseRepository<Orders> _repo;
        private readonly IBaseRepository<Books> _bookRepo;
        private readonly IBaseRepository<Customer> _customerRepo;

        public OrdersController(IBaseRepository<Orders> repository,
            IBaseRepository<Books> bookRepo,
            IBaseRepository<Customer> customerRepo)
        {
            _repo = repository;
            _bookRepo = bookRepo;
            _customerRepo = customerRepo;
        }
        public IActionResult Index()
        {
            var orders = _repo.GetAll();
            return View(orders);
        }

        public IActionResult Details(int Id)
        {
            var orders = _repo.Find(Id);
            return View(orders);
        }
        public IActionResult Create()
        {
            ViewBag.book = _bookRepo.GetAll();
            ViewBag.customer = _customerRepo.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Orders orders)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.book = _bookRepo.GetAll();
                ViewBag.customer = _customerRepo.GetAll();
                return View(orders);
            }
            _repo.Add(orders);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int Id)
        {
            ViewBag.book = _bookRepo.GetAll();
            ViewBag.customer = _customerRepo.GetAll();
            var orders = _repo.Find(Id);
            return View(orders);
        }
        [HttpPost]
        public IActionResult Edit(Orders orders)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.book = _bookRepo.GetAll();
                ViewBag.customer = _customerRepo.GetAll();
                return View(orders);
            }
            _repo.Update(orders);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int Id)
        {
            ViewBag.book = _bookRepo.GetAll();
            ViewBag.customer = _customerRepo.GetAll();
            var orders = _repo.Find(Id);
            return View(orders);
        }

        [HttpPost]
        public IActionResult Delete(Orders orders)
        {
            _repo.Delete(orders);
            return RedirectToAction(nameof(Index));
        }
    }
}

GhamdanAlYamaniProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Al-YamaniProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GhamdanAlYamaniProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> *AlYamaniProject* </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catagory" asp-action="Index">Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookStor" asp-action="Create">BookStor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Conclusion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; _2023_ - ( GhamdanAlYamaniProject ) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Go To Conclusion Page</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>